### ISSUE TITLE
请问一下，这个分段控件可以放在导航栏上吗

### ISSUE THREAD

**Issue by monkeyRing** [HJTXX/XXPageTabView#1]

**Comment by HJTXX** [comment]
不行哦，导航栏上一般使用的是单独的segmentControl类似的组件，再对下面的view进行联动，导航栏分段控件和子控制器的view层级关系与该组件设计的层级关系不同，除非titleView和bodyView可以拆开分别布局到self.navigationItem.titleView和self.view。
这个我有时间思考下能否兼容两种需求，建议你急用的话，基础实现其实比较简单，效果的话可以参考该组件代码~

**Comment by monkeyRing** [comment]
恩。我准备参照你的实现，重新封装一个单独的分段控件。

**Comment by HJTXX** [comment]
恩恩，有问题多交流
