### ISSUE TITLE
界面不加载

### ISSUE THREAD

**Issue by fuxidream** [HJTXX/XXPageTabView#3]
当我加了四个UIViewController时，其中有一个VC中的TableViewCell不加载，不知道是怎么回事

**Comment by HJTXX** [comment]
1.你可以尝试更改不显示VC的顺序，看看是不是始终是同一个VC不显示；
2.可以去掉该VC，看遗留的三个VC能不能正常显示；
3.VC视图的加载是在同一个scrollview上，不会出现某一个VC的视图不显示的情况，可以设置VC视图背景色观察图层；
