### ISSUE TITLE
添加的控制器可以动态的添加吗？控制器用于显示H5，但是显示出来的，加载很卡，而且滑动过来是显示上一个页面的内容，停留2秒之后再刷新出新的内容

### ISSUE THREAD

**Issue by MansionWayh** [HJTXX/XXPageTabView#7]
这个问题有什么解决的方案

**Comment by HJTXX** [comment]
可以通过reloadChildControllers:childTitles来重定义pageTab，并且会保持原有索引，titles和vcs应数量一致，否则跟随最小数量；
如果使用同一个VC显示H5，显示上一页再显示下一页是必然的结果，因为VC从页面1到页面2的过程均暴露在外，可以使用WKWebView来创建多个VC，避免UIWebView的内存占用过高，如果还需要进一步减少VC数量，比如创建三个然后循环使用，就需要修改组件代码来支持不对等数量的动态添加；
至于加载卡的问题，如果是多个VC同时在初始化时加载，需要将加载资源放在pageTabViewDidEndChange中来操作，只加载当前展示的内容，但H5的加载卡顿问题较多，可检查单独加载H5是否卡顿，H5的加载还是比较消耗资源的，看H5的具体内容
