### ISSUE TITLE
报错  是我的使用方法有问题么

### ISSUE THREAD

**Issue by Victor1104** [HJTXX/XXPageTabView#8]
![10a7abf3-5718-4d6f-a949-cde4c2caa857](https://user-images.githubusercontent.com/20557527/40094000-39edfb7a-58f7-11e8-8478-f049a4d88581.png)

![9983e855-0b55-4cf0-aed5-e8095ad82741](https://user-images.githubusercontent.com/20557527/40094031-5e06ce6a-58f7-
![6c6e04d8-a7d2-4791-91b8-039647f3bdde](https://user-images.githubusercontent.com/20557527/40094051-763c3830-58f7-11e8-9987-2fe128621644.png)
11e8-9ff0-3f83e99c85bb.png)

**Comment by HJTXX** [comment]
你这两个tableView不是VC吧
